In [1]:
import numpy as np


In [2]:
a= np.array([0,1,2,3,4])

In [4]:
type(a)

numpy.ndarray

In [ ]:
#indexing and slicing


In [5]:
a[0] = 100 #will change the zeroth index to 100

In [7]:
a[4] = 3 #will change the 5th element to 3


In [8]:
d = a[1:4] #will slice the row from first index to 3rd one 4th will not be considered  and store it in d variable

In [11]:
d[1:5] = 300,400  #this will change the values of 1st index element to 300 and will add a new elemetn

In [ ]:
#numpy statistical functions

In [14]:
#.mean() for calculation of the mean of the given data that is given here
mean_data = d.mean()
mean_data


np.float64(233.66666666666666)

In [15]:
# .std() for calculating the standard deviation of the given data
standard_deviation = d.std()
standard_deviation

np.float64(169.50975062088773)

In [17]:
# .max() for finding the max value or the biggest value in  the numpy array 
max_value = d.max()
max_value

np.int64(400)

In [18]:
min_value = d.min()
min_value

np.int64(1)

In [19]:
u = np.array([1,2,3])

In [20]:
v = np.array([2,3,4])

In [22]:
#numpy array addition .add() or vector addition
z = np.add(u,v)
z

array([3, 5, 7])

In [24]:
#numpy array subtraction .subtract() or vector subtraction
z = np.subtract(v,u)
z

array([1, 1, 1])

In [25]:
#numpy array multiplication .multiply() or vector multiply
z = np.multiply(u,v)
z

array([ 2,  6, 12])

In [ ]:
#numpy array division .divide() or vector divide


In [26]:
z = np.divide(u,v)
z

array([0.5       , 0.66666667, 0.75      ])

In [28]:
#numpy array dot product .dot() or vector dot product
z = np.dot(u,v)
z

np.int64(20)

In [29]:
#adding the constant to the Numpy array
u = np.array([1,2,3])
u+1
#1 will be adding to every element of the array 

array([2, 3, 4])

In [30]:
np.pi

3.141592653589793

In [32]:
x = np.array([0, np.pi/2 , np.pi])
x

array([0.        , 1.57079633, 3.14159265])

In [33]:
y = np.sin(x)
y

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [36]:
# linspace  -  useful mathematical function which is used for plotting mathematical funtions is linspace as linspace would return evenly spaced numbers
np.linspace(-2,2,num=7)

array([-2.        , -1.33333333, -0.66666667,  0.        ,  0.66666667,
        1.33333333,  2.        ])

In [37]:
y= np.linspace(2,10,num=50)

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [ ]:
# .sin() to each element 